### ISSUE TITLE
Descarga masiva: ValueError: 0 is not a valid EstadoSolicitud

### ISSUE THREAD

**Issue by arielmol** [SAT-CFDI/python-satcfdi#13]
En algunos raros casos sale este bug:

```python
2023-08-08 14:00:03 (CDT) Descargar recibidas
Traceback (most recent call last):
  File "/home/admin/descarga_masiva/cfdi-descarga-masiva.py", line 59, in <module>
    for paquete_id, data in sat_service.recover_comprobante_iwait(
  File "/home/admin/miniconda3/envs/sat-cfdi/lib/python3.10/site-packages/satcfdi/pacs/sat.py", line 645, in recover_comprobante_iwait
    response = self.recover_comprobante_status(
  File "/home/admin/miniconda3/envs/sat-cfdi/lib/python3.10/site-packages/satcfdi/pacs/sat.py", line 570, in recover_comprobante_status
    return self._execute_req(
  File "/home/admin/miniconda3/envs/sat-cfdi/lib/python3.10/site-packages/satcfdi/pacs/sat.py", line 363, in _execute_req
    return req.process_response(xml)
  File "/home/admin/miniconda3/envs/sat-cfdi/lib/python3.10/site-packages/satcfdi/pacs/sat.py", line 250, in process_response
    return descarga_result(res)
  File "/home/admin/miniconda3/envs/sat-cfdi/lib/python3.10/site-packages/satcfdi/pacs/sat.py", line 240, in descarga_result
    result['EstadoSolicitud'] = Code(estado_solicitud, EstadoSolicitud(estado_solicitud).name)
  File "/home/admin/miniconda3/envs/sat-cfdi/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/home/admin/miniconda3/envs/sat-cfdi/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 0 is not a valid EstadoSolicitud
```

Eso es de un _cron job_ que periódicamente descarga facturas cada 24 horas, sucede como una vez cada uno o dos días.

Podría ser el SAT mismo, pero parece que sí manda un valor 0. No se.

**Comment by satcfdi** [comment]
Resuelto en version 4.2.2
