### ISSUE TITLE
404 Error no controlado.

### ISSUE THREAD

**Issue by arielmol** [SAT-CFDI/python-satcfdi#19]
Recientemente al pedir algunos paquetes de CFDI en masa:
```python
    if (direccion == "recibidas"):
        for paquete_id, data in sat_service.recover_comprobante_iwait(
                fecha_inicial=initial.datetime,
                fecha_final=today.datetime,
                rfc_receptor=sat_service.signer.rfc,
                tipo_solicitud=TipoDescargaMasivaTerceros.CFDI ):
            filename = f"{folder}/{fmttoday}_{paquete_id}_RE.zip"
            with open(filename, "wb") as f:
                f.write(data)
                print("OK:", filename)
```

Me sale este error nuevo:

```python
Traceback (most recent call last):
  File "/home/admin/apps/rocket-api/current/tools/cfdi/cfdi-descarga-masiva.py", line 78, in <module>
    for paquete_id, data in sat_service.recover_comprobante_iwait(
  File "/home/admin/miniconda3/envs/sat-cfdi/lib/python3.10/site-packages/satcfdi/pacs/sat.py", line 688, in recover_comprobante_iwait
    _service_logger("VerificaSolicitudDescargaResult", response)
  File "/home/admin/miniconda3/envs/sat-cfdi/lib/python3.10/site-packages/satcfdi/pacs/sat.py", line 100, in _service_logger
    raise ResponseError(response)
satcfdi.exceptions.ResponseError: {'IdsPaquetes': [], 'CodEstatus': '404', 'EstadoSolicitud': 0, 'NumeroCFDIs': 0, 'Mensaje': 'Error no controlado.'}
```

Antes no salia o no lo habia notado. Sé que sí hay CFDIS porque otras herramientas sí los descargan.

**Comment by satcfdi** [comment]
Creo que te recomendaria llamar los metodos internos
- recover_comprobante_request
- recover_comprobante_status
- recover_comprobante_download
ya que en el metodo de iwait cualquier execepcion iterumpiria el processo

**Comment by satcfdi** [comment]
https://satcfdi.readthedocs.io/en/latest/pages/getting_started/45_cfdi_descarga_massiva.html

**Comment by arielmol** [comment]
Pude replicarlo siguiendo tu ejemplo si pones un espacio, por ej

```python
In [71]: sat_service.recover_comprobante_status(" 0550c148-bec3-4aa1-b61d-***********")
Out[71]: 
{'IdsPaquetes': [],
 'CodEstatus': '404',
 'EstadoSolicitud': 0,
 'NumeroCFDIs': 0,
 'Mensaje': 'Error no controlado.'}
```

**Comment by arielmol** [comment]
Al parecer nomas le falta un strip() en algun lugar por ahi
